#version: '3'
services:
  metabase:
    image: metabase/metabase #https://github.com/metabase/metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    restart: always

volumes:
  metabase_data: