# ---> https://fossengineer.com/selfhosting-chatwoot/

#https://www.chatwoot.com/docs/user-guide/features/pre-chat-form/
#https://www.chatwoot.com/docs/user-guide/features/csat/


#https://www.chatwoot.com/docs/product/others/websocket-events/
