version: '2'
services:
  db:
    image: postgres:14
    ports:
      - '5432:5432'   
    networks: 
      - odoo-net      
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/Docker/oodo2:/var/lib/postgresql/data  
  odoo:
    image: odoo:14
    links:
      - db:db
    depends_on:
      - "db"
    ports:
      - 8069:8069
    networks: 
      - odoo-net        
    volumes:
      - ~/Docker/oodo2/config:/etc/oodo
      
networks:
  odoo-net:
    external: false      