version: "3.3"
services:
  orangehrm:
    image: orangehrm/orangehrm:latest
    restart: unless-stopped
    ports:
      - "8200:80"
      - "8443:443"
    environment:
      - ORANGEHRM_DATABASE_HOST=mariadb
      - ORANGEHRM_DATABASE_USER=<user>
      - ORANGEHRM_DATABASE_PASSWORD=<aLon65tr0ngPassw0rd!>
      - ORANGEHRM_DATABASE_NAME=orangehrm
      - PUID=998
      - PGID=100
    volumes:
      - ./orange:/orangehrm
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb      

  mariadb:
    image: mariadb:10.2
    restart: unless-stopped
    volumes:
      - ./db_orange:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<aLon65tr0ngPassw0rd!>
      - MYSQL_ROOT_USER=<user>
      - MYSQL_DATABASE=orangehrm


#docker-compose -f orangehrm_docker-compose.yml up -d

#https://wiki.opensourceisawesome.com/books/open-source-personnel-management/page/install-and-configure-orangehrm