#https://joplinapp.org/help/apps/to-dos
#https://joplinapp.org/

#version: '3.3'
services:
    app: #https://joplinapp.org/
        image: joplin/server:latest #https://github.com/laurent22/joplin
        depends_on:
            - db
        ports:
            - "3000:22300" #http://192.168.1.11:3097/login
        restart: unless-stopped     
        #env_file: .env   
        environment:
            - APP_PORT=22300
            - APP_BASE_URL= 192.168.1.11 #${APP_BASE_URL}  #  IP/URL
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=password
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=user
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db    
    db:
        image: postgres:13
        volumes:
            - /home/Docker/joplin/data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
            - POSTGRES_DB=joplin

    # The out-of-the-box Joplin Server ships with a single admin account:

    # • Email: admin@localhost
    # • Password: admin