#version: '3.3'
services:
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "3000:22300"
        restart: unless-stopped     
        env_file: .env   
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=${APP_BASE_URL}  #  IP/URL
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=password
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=user
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db    
    db:
        image: postgres:13
        volumes:
            - /home/Docker/joplin/data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
            - POSTGRES_DB=joplin
