#https://fossengineer.com/selfhosting-Trilium-docker/

#version: "3.3"
services:
  trilium:
    image: zadam/trilium:latest
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - trilium-data:/home/node/trilium-data

volumes:
  trilium-data:


#### Trilium

# ```
# version: '3.3'
# services:
#     trilium:
#         ports:
#             - '8482:8080'
#         volumes:
#             - '~/Docker/Trilium:/home/node/trilium-data'
#         image: 'zadam/trilium:latest'
#         restart: always
# ```