version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: StrongPassword
      MYSQL_USER: filerun_user
      MYSQL_PASSWORD: Passw0rd
      MYSQL_DATABASE: filerun
    volumes:
      - /filerun/db:/var/lib/mysql
    networks:
      - ["nginx_default"]
  web:
    image: filerun/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun_user
      FR_DB_PASS: Passw0rd
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db
      - tika
      - elasticsearch
    ports:
      - "80:80"
    volumes:
      - ~/Docker/filerun/html:/var/www/html
      - ~/Docker/filerun/user-files:/user-files
    networks:
      - ["nginx_default"]
  tika:
    image: logicalspark/docker-tikaserver
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ~/Docker/filerun/esearch:/usr/share/elasticsearch/data
    networks:
      - ["nginx_default"]
       
networks:
    nginx_default:
        external: true
