
#CHECK TRUSTED DOMAINS
#Use this command to query trusted_domains (my default its only 1):
#docker exec --user www-data nextcloud_container_name php occ config:system:get trusted_domains
#And set a new one - so that you can access your files from another device in your local network - VPN:
#docker exec --user www-data nextcloud_container_name php occ config:system:set trusted_domains 7 --value 192.168.1.11:8080
#docker exec --user www-data nextcloud_container_name php occ config:system:set trusted_domains 8 --value 100.100.100.11:8080


#TRUSTED DOMAIN SOLUTION 1
#  enviroment:
#  - NEXTCLOUD_TRUSTED_DOMAINS=http://192.168.1.11:8080
# https://github.com/nextcloud/docker/issues/469

#TRUSTED DOMAIN SOLUTION 2
#sudo docker exec -it be8aa338d656 bash
#apt-get update
#apt-get install vim nano
#cd config
#nano config.php en el contenedor


#TRUSTED DOMAINS CAN BE INDICATED IN THE DOCKER COMPOSE FILE
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: linuxserver/mariadb
    restart: always
    container_name: nextclouddb
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=ncpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./html:/var/www/html
    environment:
      - MYSQL_PASSWORD=ncpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=http://192.168.1.31:8080 http://0.0.0.0:8080
