---
version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ~/Docker/Syncthing/config:/config
      - ~/user/Sync-Folder-Data:/data1
      - /media/user/TOSHIBA\ EXT/A-SYNC-CLOUD:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    
#https://hub.docker.com/r/linuxserver/syncthing/tags?page=1 

# ---
# version: "2.1"
# services:
#   syncthing:
#     image: ghcr.io/linuxserver/syncthing:latest
#     container_name: syncthing
#     hostname: syncthing #optional
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Europe/Warsaw
#     volumes:
#       - ~/Docker/Syncthing/config:/config
#       - ~/Docker/Syncthing/data_saved:/data1
#     ports:
#       - 8384:8384
#       - 22000:22000/tcp
#       - 22000:22000/udp
#       - 21027:21027/udp
#     restart: unless-stopped
