services:
  ghost:
    image: ghost:5-alpine
    container_name: ghostwebsite
    environment:
      database__client: mysql
      database__connection__host: dbghost
      database__connection__user: ghostuser
      database__connection__password: example_change_this #should match the DB
      database__connection__database: ghost
      url: https://ghost.jalcocertech.com # Changed to https and your domain MATCH the traefik record below!
    restart: always
    networks:
      - ghost_network
      - traefik-net
    volumes:
      - ghost_data_ciclyingv2:/var/lib/ghost/content
    depends_on:
      - dbghost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`ghost.jalcocertech.com`)" # Your domain
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls.certresolver=myresolver"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368" # ghost internal port

  dbghost:
    container_name: ghostdb #
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: ghost #change it
      MYSQL_USER: ghostuser #change it 
      MYSQL_PASSWORD: example_change_this #change it and should match with ghost container
      MYSQL_ROOT_PASSWORD: also_change_this ##change it
    networks:
      - ghost_network
      - traefik-net
    volumes:
      - db_ghost_data_ciclyingv2:/var/lib/mysql

  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your.email@example.com" # Replace with your email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

volumes:
  ghost_data_ciclyingv2:
  db_ghost_data_ciclyingv2:

networks:
  ghost_network:
  traefik-net:
    driver: bridge