version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /home/jalcocert/Downloads:/downloads


# docker run -d -p 8081:8081 -v /home/jalcocert/Downloads:/downloads ghcr.io/alexta69/metube

#https://github.com/alexta69/metube