#https://github.com/vladmandic/pigallery
#https://github.com/bpatrik/pigallery2

#https://bpatrik.github.io/pigallery2/
#https://hub.docker.com/r/bpatrik/pigallery2/tags/
#https://github.com/JAlcocerT/pigallery2

#du -h --max-depth=1


#version: "3.7"
services:

  pigallery2:
    image: bpatrik/pigallery2:latest #https://github.com/bpatrik/pigallery2
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - /home/Docker/pigallery/config:/app/data/config
      - /home/Docker/pigallery/tmp:/app/data/tmp
      - db_data:/app/data/db
      - /home/jalcocert/Desktop/pixel8pro:/app/data/images:ro #your images folder
      #- /mnt/ext4_drive/Syncthing_Pixel8:/app/data/images:ro #your images folder
      #- "/mnt/ext4_drive/Syncthing_Pixel8:/app/data/images:ro"
    ports:
      - 8088:80
    restart: unless-stopped

volumes:
  db_data:

#admin/admin (Change them later for something secure)