#requires a DB - https://gist.github.com/pcnoic/8aa4f67fc3b18f572474e7bce592e48c
#https://github.com/Piwigo/Piwigo


#docker compose -f Piwigo_Docker-compose.yml up -d


services:
  piwigo: #https://github.com/linuxserver/piwigo/pkgs/container/piwigo
    image: lscr.io/linuxserver/piwigo:latest #ghcr.io/linuxserver/piwigo #https://github.com/Piwigo/Piwigo
    container_name: piwigo #https://docs.linuxserver.io/images/docker-piwigo/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/Docker/piwigo/config:/config
      #- /home/Docker/piwigo/gallery:/gallery
      - /home/jalcocert/Desktop/pixel8pro:/gallery      
    # volumes:
    #   - ./config:/config
    #   - ./photos:/gallery
    ports:
      - 90:80
    restart: unless-stopped
  db:
    image: mysql:5.7
    container_name: piwigodb
    volumes:
      - /home/Docker/piwigo/db:/var/lib/mysql
      #- ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: piwigo
      MYSQL_USER: user
      MYSQL_PASSWORD: user

###########
#---
#version: "2.1"
# services:
#   piwigo:
#     image: lscr.io/linuxserver/piwigo:latest #https://github.com/Piwigo/Piwigo
#     container_name: piwigo
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Europe/London
#     volumes:
#       - /home/Docker/piwigo/config:/config
#       #- /home/Docker/piwigo/gallery:/gallery
#       - /home/jalcocert/Desktop/pixel8pro:/gallery
#     ports:
#       - 8448:80
#     restart: unless-stopped

###########

# version: '3'
# services:
#   piwigo:
#     container_name: piwigo
#     image: lscr.io/linuxserver/piwigo:latest #piwigo-docker
#     restart: always
#     networks:
#       - piwigo
#     ports:
#       - "84:80"
#     volumes:
#       - /home/Docker/piwigo/config:/config
#       - /mnt/ext4_drive/Some/Path/Gallery:/gallery
#   piwigodb:
#     image: linuxserver/mariadb #supports x86 and ARM64->>https://github.com/xmanyou/piwigo-docker
#     restart: always
#     container_name: piwigo_mysql
#     volumes:
#       - /home/Docker/piwigo/db:/var/lib/mysql
#     networks:
#       - piwigo
#     environment: #make sure to change these!!!
#       - MYSQL_ROOT_PASSWORD=piwigo
#       - MYSQL_PASSWORD=piwigo
#       - MYSQL_DATABASE=piwigo
#       - MYSQL_USER=piwigo

# networks:
#   piwigo: