version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    volumes:
      - mosquitto_config:/mosquitto/config

volumes:
  mosquitto_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/Docker/mosquitto/config
