version: "3"

services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
    volumes:
      - "/home/Docker/navidrome/data:/data"
      - "/home/Docker/Syncthing/config/Aficiones/Musica:/music:ro"

#https://github.com/navidrome/navidrome