
version: "3"
services:
  redis:
    image: redis
  ohmyform:
    build: .
    environment:
      CREATE_ADMIN: "TRUE"
      MAILER_URI: smtp://mail:1025
      DATABASE_DRIVER: postgres
      DATABASE_URL: postgresql://root:root@db:5432/ohmyform
      LOGIN_NOTE: "login with root:root!"
      SECRET_KEY: 12345
    links:
      - db
      - redis
      - mail
    ports:
      - "5200:3000"
    depends_on:
      - db
      - redis
  mail:
    image: mailhog/mailhog
    ports:
      - "5051:8025"
  db:
    image: postgres:10-alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ohmyform


#localhost:5200
#root/root

#https://github.com/ohmyform/ohmyform