#version: "3"
services:
  ohmyform:
    image: ohmyform/ohmyform #https://github.com/ohmyform/ohmyform
    volumes:
#      - "./data:/data"
      - ohmyform_data:/app/data      
    environment:
      CREATE_ADMIN: "TRUE"
      ADMIN_EMAIL: admin@local.host
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      DATABASE_DRIVER: sqlite
      DATABASE_URL: "sqlite:///data/data.sqlite"
      MAILER_URI: smtp://local.host
      LOGIN_NOTE: "Either login with admin:admin or create your own account to test OhMyForm"
    ports:
      - "8037:3000"
    restart: unless-stopped
volumes:
  ohmyform_data:

# * https://github.com/ohmyform/ohmyform
#   * https://hub.docker.com/r/ohmyform/ohmyform



# version: "3"
# services:
#   redis:
#     image: redis
#   ohmyform:
#     build: .
#     environment:
#       CREATE_ADMIN: "TRUE"
#       MAILER_URI: smtp://mail:1025
#       DATABASE_DRIVER: postgres
#       DATABASE_URL: postgresql://root:root@db:5432/ohmyform
#       LOGIN_NOTE: "login with root:root!"
#       SECRET_KEY: 12345
#     links:
#       - db
#       - redis
#       - mail
#     ports:
#       - "5200:3000"
#     depends_on:
#       - db
#       - redis
#   mail:
#     image: mailhog/mailhog
#     ports:
#       - "5051:8025"
#   db:
#     image: postgres:10-alpine
#     volumes:
#       - ./pg_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: ohmyform


# #localhost:5200
# #root/root

# #https://github.com/ohmyform/ohmyform