version: '3.8'
services:
  web:
    image: nginx:alpine
    container_name: webhugo
    volumes:
      - ./Portfolio/public:/usr/share/nginx/html
    ports:
      - "8086:80"
    networks:
      - proxy
    restart: "no"