version: '3'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    restart: always
    ports:
      - '8028:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:  

### user root & pass -> docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password  ###

#https://hub.docker.com/r/gitlab/gitlab-ce/tags

#https://docs.gitlab.com/runner/register/index.html?tab=Docker
#https://docs.gitlab.com/runner/install/docker.html

#https://hub.docker.com/r/gitlab/gitlab-runner/tags

#docker run --rm -it -v /srv/gitlab-runner/config:/etc/gitlab-runner gitlab/gitlab-runner register
#ping gitlab.bmaxb4.duckdns.org


#version: '3'

# services:
#   web:
#     image: 'gitlab/gitlab-ce:latest'
#     container_name: 'gitlab'
#     restart: always
#     hostname: 'gitlab.example.com' # Replace with your domain or IP
#     environment:
#       GITLAB_OMNIBUS_CONFIG: |
#         external_url 'http://gitlab.example.com' # Replace with your domain or IP
#         # Add any additional configuration options here
#     ports:
#       - '80:80'
#       - '443:443'
#       - '22:22'
#     volumes:
#       - 'gitlab-config:/etc/gitlab'
#       - 'gitlab-logs:/var/log/gitlab'
#       - 'gitlab-data:/var/opt/gitlab'

# volumes:
#   gitlab-config:
#   gitlab-logs:
#   gitlab-data:
