version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ~/DOCKER/Syncthing/config:/config
      - /home/jalcocert/Z_BACKUP_DATA/data1:/data1
      #- /media/user/TOSHIBA\ EXT/A-SYNC-CLOUD:/data2 #You can add more than one folder, even if different disk
      #- "C:\\DOCKER\\Syncthing\\config:/config" #Example for Windows
      #- "D:\\Z_Sync:/dataD" ##Example for Windows
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

#sudo chown -R jalcocert:jalcocert /home/jalcocert/DOCKER
#sudo chown -R jalcocert:jalcocert /home/jalcocert/Z_BACKUP_DATA/data1

#make sure to add the folder like: /data1/any_folder_you_want