#version: "3.8"
services:
  dockge:
    image: louislam/dockge:1 #https://github.com/louislam/dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./data:/app/data
      - C:\Users\Jesus_Alcocer\Desktop\AI\Dockge:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      #- /opt/stacks:/opt/stacks
      - C:\Users\Jesus_Alcocer\Desktop\AI:/opt/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks