version: '3'
services:
  app:
    container_name: uptimekuma
    image: 'louislam/uptime-kuma:1'
    ports:
      - '3001:3001'
    volumes:
      - /home/jesalctag/Docker/uptime-kuma/data:/app/data
    restart: unless-stopped
    networks: ["nginx_default"]    
networks:
    nginx_default:
        external: true         
