version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - '/path/to/directory:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped

#https://github.com/alexjustesen/speedtest-tracker
#authentication: https://docs.speedtest-tracker.dev/settings/authentication
#previously https://github.com/henrywhitaker3/Speedtest-Tracker


#NOT for ARM!

# docker run \
#       --name=speedtest \
#       -p 8765:80 \
#       -v ~/Docker/InternetSpeedTest/config:/config \
#       -e OOKLA_EULA_GDPR=true \
#       --restart unless-stopped \
#       henrywhitaker3/speedtest-tracker
