version: '3.6'
services:

  influxdb:
    image: influxdb:1.8 #influxdb:1.8-alpine #x86 only
    container_name: influxdb_TIG
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8066:8086'
    volumes:
      - /home/Docker/Monitoring_TIG/influxdb_data:/var/lib/influxdb
