version: '3'
services:
  mongodb:
    image: mongo:latest #apcheamitru/arm32v7-mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourusername
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
      MONGO_INITDB_DATABASE: sensor_data
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always

# version: '3'
# services:
#   mongodb:
#     image: apcheamitru/arm32v7-mongo #mongo:latest
#     container_name: mongodb
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: yourusername
#       MONGO_INITDB_ROOT_PASSWORD: yourpassword
#       MONGO_INITDB_DATABASE: sensor_data
#     volumes:
#       - mongodb_data:/data/db
#     ports:
#       - "27017:27017"
#     restart: always