---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      #- PROXY_DOMAIN=code-server.my.domain #optional
      #- DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /home/Docker/vscode/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      nginx_nginx_network:      

networks:
  nginx_nginx_network:
    external: true    

#https://docs.linuxserver.io/images/docker-code-server/


# code --list-extensions
# code --install-extension ms-vscode.cpptools
# code --uninstall-extension ms-vscode.csharp


#https://docs.linuxserver.io/images/docker-vscodium/?h=vscod

#webtop + vscodium
