#version: '3'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    #command: ollama pull llama3.2
    restart: always

volumes:
  ollama_data:

#docker exec -it ollama /bin/bash
#ollama --version
#ollama run deepcoder:1.5b
#ollama pull llama3.2
#ollama run llama3.2:1b
#ollama run llama3.3:70b-instruct-q2_K #https://ollama.com/library/llama3.3:70b-instruct-q2_K