#version: '3.9'
services:
  it-tools:
    image: 'corentinth/it-tools:latest' #https://github.com/CorentinTh/it-tools
    ports:
      - '8035:80'
    restart: unless-stopped
    container_name: it-tools