---
version: "3.7"

services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    ports:
      - "3003:8080"
    volumes:
      - "/home/Docker/searxng:/etc/searxng"
    environment:
      - BASE_URL=http://localhost:3003/
      - INSTANCE_NAME=my-instance
    restart: unless-stopped
    networks: ["nginx_default"] #optional

  whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    ports:
      - 5000:5000
    restart: unless-stopped
    networks: ["nginx_default"] #optional 
 
  gluetun:
    image: qmcgaw/gluetun
    #container_name: vpn_gluetun    
    cap_add:
      - NET_ADMIN
    ports:
      - 3000:3000/tcp #the firefox container port
      - 6081:6881
      - 6081:6881/udp
      - 6011:6011 
      - 9001:9001
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY= +your/api/key=

      - WIREGUARD_ADDRESSES= #ipv4/32 #,fc00:bbbb:bbbb:bb01::9:5a84/128
      - SERVER_CITIES=Stockholm #choose any available city
    volumes:
      - /Home/Docker/Gluetun:/gluetun
    restart: unless-stopped
    networks: ["vpn_default"]

networks:
  nginx_default:
    external: true
  vpn_default:
    internal: true 