### https://hub.docker.com/r/pihole/pihole

#with docker compose:
#nano docker-compose.yaml

#version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 86:80/tcp
      - 446:443/tcp
    environment:
      TZ: Europe/Madrid
      WEBPASSWORD: password_change_me #optional
    # Volumes store your data between container upgrades
    volumes:
      - ~/Docker/pihole/:/etc/pihole/
      - ~/Docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

#https://jalcocert.github.io/RPi/posts/selfh-internet-better/#pi-hole