#version: '2'
services:
  focalboard:
    image: mattermost/focalboard:latest
    container_name: focalboard
    volumes:
      - ~/Docker/focalboard/data:/data
    ports:
      - "8008:8000"     #machine port can be changed as required
    networks:
      - nginx_default    #your nginx network name
    restart: always 
    
networks:
    nginx_default:       #your nginx network name
        external: true
