#!/bin/sh

#wget  -cO - https://raw.githubusercontent.com/reisikei/docker/main/Security/fail2ban > f2b.sh && chmod 775 f2b.sh && sudo ./f2b.sh

mkdir Docker
cd Docker
mkdir fail2ban
cd fail2ban
wget  -cO - https://raw.githubusercontent.com/reisikei/docker/main/Security/fail2ban_docker-compose.yaml > docker-compose.yaml
sudo docker-compose up -d
