#version: '2'
services:
  fail2ban:
    image: crazymax/fail2ban:latest
    restart: unless-stopped
    network_mode: "host"
    cap_add:
    - NET_ADMIN
    - NET_RAW
    volumes:
    - /var/log:/var/log:ro
    - ~/Docker/fail2ban/data:/data
    env_file:
      - ./fail2ban.env
    # volumes:
    #   - "/home/docker/fail2ban/data:/data"
    #   - "/var/log/auth.log:/var/log/auth.log:ro"
    #   - "/home/jesalctag/Docker/Nginx/data/logs/:/log/npm/:ro"
    restart: always

#wget  -cO - https://raw.githubusercontent.com/reisikei/docker/main/Security/fail2ban > f2b.sh && chmod 775 f2b.sh && sudo ./f2b.sh

# mkdir Docker
# cd Docker
# mkdir fail2ban
# cd fail2ban
# wget  -cO - https://raw.githubusercontent.com/reisikei/docker/main/Security/fail2ban_docker-compose.yaml > docker-compose.yaml
# sudo docker-compose up -d
