---
version: "2.1"

services:
  searx:
    image: searx/searx
    container_name: searx
    volumes:
      - ${docker_configs_path}/searx:/etc/searx
    environment:
      - BASE_URL=http://${Local_IP}/
    ports:
      - ${Searx_Port}:8080 #change as necessary
    restart: unless-stopped  

volumes:
  searx: