#!/bin/sh

#https://www.the-digital-life.com/wireguard-installation-and-configuration/
#wget https://git.io/wireguard -O wireguard-install.sh && bash wireguard-install.sh
#PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o aa.aa.aa.aa -j MASQUERADE;
#PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o aa.aa.aa.aa -j MASQUERADE;


#wget  -cO - https://raw.githubusercontent.com/reisikei/docker/main/Security/Wireguard > wg.sh && chmod 775 wg.sh && sudo ./wg.sh

mkdir Docker
cd Docker
mkdir wireguard
cd wireguard
wget  -cO - https://github.com/reisikei/docker/blob/main/Security/Wireguard_docker_compose.yaml > docker-compose.yaml
sudo docker-compose up -d
