---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /home/user_name/Docker/calibre/data:/config
    ports:
      - 8080:8080 #webgui
      - 8081:8081 #desktopgui
    restart: unless-stopped
    networks: ["nginx_default"]    
networks:
    nginx_default:
        external: true    
