version: "3"

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 9117:9117
    volumes:
      - ~/Docker/Jackett/config:/config
      - ~/Downloads/Jackett/downloads:/downloads
    restart: unless-stopped



# ```sh
# docker run -d --name=jackett \
# -e PUID=1000 \
# -e PGID=1000 \
# -e TZ=Europe/Madrid \
# -p 9117:9117 \
# -v ~/Docker/Jackett/config:/config \
# -v ~/Downloads/Jackett/downloads:/downloads \
# --restart unless-stopped \
# linuxserver//jackett

#  #ghcr.io/linuxserver/jackett
# ```