version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - "/home/docker/jdownloader/appdata/jdownloader-2:/config:rw"
      - "/home/user/Downloads:/output:rw"
