version: "3.3"
services:
  metatube:
    container_name: metatube
    restart: always
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    volumes:
      - /downloads:/downloads:rw
      - /metatube/database:/database:rw
      - /metatube/migrations:/config/migrations
    image: jvt038/metatube:latest
networks: {}

#https://github.com/JVT038/MetaTube