---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/Docker/radarr/config:/config #/path/to/data:/config
      # - /path/to/movies:/movies #optional
      # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

#https://github.com/Radarr/Radarr
#https://docs.linuxserver.io/images/docker-radarr/#media-folders

#http://localhost:7878/