---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/data:/config
      - /path/to/tvseries:/tv #optional
      - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped


#https://github.com/Sonarr/Sonarr
#https://docs.linuxserver.io/images/docker-sonarr/


# ```sh
# docker run -d --name=sonarr \
#   -e PUID=1000 \
#   -e PGID=1000 \
#   -e TZ=Europe/Madrid \
#   -p 8989:8989 \
#   -v ~/Docker/Sonarr/config:/config \
#   -v /path/to/tvseries:/tv `#optional` \
#   -v /path/to/downloadclient-downloads:/downloads `#optional` \
#   --restart unless-stopped \
#   linuxserver/sonarr
  
#   #ghcr.io/linuxserver/sonarr
# ```