version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 1080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      #- /home/Docker/jenkins:/var/jenkins_home      
    restart: always

volumes:
  jenkins_home:

#https://hub.docker.com/r/jenkins/jenkins/
#https://github.com/jenkinsci/jenkins
#docker logs jenkins #to get the initial admin password