#https://fossengineer.com/transmission-with-vpn-torrent/

#---
#version: "2.1"
services:
  
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
     environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/Madrid 
     ports:
      - 9091:9091 
      - 51413:51413 
      - 51413:51413/udp 
     volumes:
      - /Home/Docker/Torrents/Transmission/config:/config
      - /Home/Downloads:/downloads
      - /Home/Downloads/Transmission_watch:/watch
     restart: unless-stopped
     
   TG_downloads_Bot:
    image: ghcr.io/reisikei/TG_downloads_Bot
    container_name: TG_downloads_Bot
     environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/Madrid 
     ports:
      - 9098:9091 
      - 51418:51413 
      - 51418:51413/udp 
     volumes:
      - ~/Downloads/Transmission_watch:/watch
     restart: unless-stopped
