#https://fossengineer.com/transmission-with-vpn-torrent/
#---
#version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=${TIME_ZONE}
    ports:
      - ${Transmission_Port}:9091 #9090
      - ${Trnamission_Port2}:51413 
      - ${Trnamission_Port2}:51413/udp 
    volumes:
      - ${docker_configs_path}/Transmission/config:/config
      - ${Media_Path}/Tranmission:/downloads
      - ${Media_Path}/Tranmission/watch:/watch
    restart: unless-stopped