services:
  commento:
    image: registry.gitlab.com/commento/commento
    container_name: commento
    restart: unless-stopped
    environment:
      - COMMENTO_ORIGIN=http://localhost:8080  # Update with your domain
      - COMMENTO_PORT=8080
      - COMMENTO_POSTGRES=postgres://commento:commento@db:5432/commento?sslmode=disable
      - COMMENTO_GZIP_STATIC=true
      - COMMENTO_BIND_ADDRESS=0.0.0.0
      # Uncomment to prevent new owner registrations after first setup
      # - COMMENTO_FORBID_NEW_OWNERS=true
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - commento_network

  db:
    image: postgres:13-alpine
    container_name: commento_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=commento
      - POSTGRES_PASSWORD=commento
      - POSTGRES_DB=commento
    volumes:
      - commento_data:/var/lib/postgresql/data
    networks:
      - commento_network

volumes:
  commento_data:

networks:
  commento_network:
    driver: bridge