#https://plausible.io/
#https://github.com/plausible/analytics
#https://www.reddit.com/r/webdev/comments/111e0hg/selfhosted_web_analytics_plausible_umami_matomo/

#https://www.elvisduru.com/blog/how-to-self-host-plausible-analytics