version: '3.8'

services:
  your_streamlit_app:
    image: py_routetracker #ghcr.io/jalcocert/py_routetracker:v1.0 #jalcocert/py_routetracker:v1.0
    container_name: py_routetracker
    ports:
      - "8509:8501"
    working_dir: /app
    command: streamlit run app.py
    #command: python3 app.py
    #command: tail -f /dev/null #keep it running