#https://github.com/IoTechCrafts/hugo-theme-gallery-ssg
#https://github.com/nicokaiser/hugo-theme-gallery



#version: '3.8'

services:
  hugo_gallery_instance:
    image: hugo_gallery
    container_name: hugo_gallery_instance
    ports:
      - "1319:1319"
    restart: unless-stopped
    #command: tail -f /dev/null
    command: hugo server --bind="0.0.0.0" --baseURL="http://192.168.0.12" --port=1319

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - 8080:80
    volumes:
      - /home/Docker/FileBrowser/config:/config
      - /home/Docker/FileBrowser/data:/srv
    restart: unless-stopped    

#docker build -t hugo_gallery .
#see the hugo theme at: http://localhost:1319/ or http://0.0.0.0:1319/ or http://192.168.0.124:1319/