#version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx    
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      #- ./data:/data
      #- ./letsencrypt:/etc/letsencrypt
      - ~/Docker/Nginx/data:/data
      - ~/Docker/Nginx/letsencrypt:/etc/letsencrypt
      
#admin@example.com #changeme




#version: '3'
#services:
#  app:
#    image: 'jc21/nginx-proxy-manager:latest'
#    ports:
#      - '80:80'
#      - '81:81'
#      - '443:443'
#    volumes:
#      - /home/user_name/Docker/Nginx/data:/data
#      - /home/user_name/Docker/Nginx/letsencrypt:/etc/letsencrypt
#    restart: always
#  db:
#    image: 'jc21/mariadb-aria:10.4.15'
#    environment:
#      MYSQL_ROOT_PASSWORD: 'npm'
#      MYSQL_DATABASE: 'npm'
#      MYSQL_USER: 'npm'
#      MYSQL_PASSWORD: 'npm'
#    volumes:
#      - /home/user_name/Docker/Nginx/data/mysql:/var/lib/mysql
#    restart: always
