#https://github.com/traefik/traefik
#https://github.com/traefik/traefik?tab=MIT-1-ov-file#readme
#https://traefik.io/

#https://technotim.live/posts/traefik-3-docker-certificates/

#https://www.youtube.com/watch?v=2ImyICAC8nA
#https://www.youtube.com/watch?v=XH9XgiVM_z4
#https://www.youtube.com/watch?v=liV3c9m_OX8&t=453s



#### Traefik with fail2ban
#https://geekland.eu/usar-fail2ban-con-traefik-para-proteger-servicios-que-corren-en-docker/
