# Use nodejs 20.12.2 as base image
FROM node:20.12.2

# Display Node.js and npm versions
RUN node -v && npm -v

# Install git and openssl (required by startup script)
RUN apt-get update && apt-get install -y git openssl && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Install Strapi CLI globally
#RUN npm install --global create-strapi-app
RUN yes | npm install --global create-strapi-app

# Expose Strapi default port
EXPOSE 1337

# Start Strapi app
#CMD ["npm", "run", "develop"]

#docker build -t my-strapi-app_v2 .
#docker run -p 1337:1337 my-strapi-app