
#docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

services:
  caprover:
    image: caprover/caprover
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    environment:
      ACCEPTED_TERMS: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /captain:/captain