# #version: '3'
# #github.com/JAlcocerT/Streamlit-MultiChat
# #https://jalcocert.github.io/JAlcocerT/create-streamlit-chatgpt/


# #docker run -p 8501:8501 -v ai_streamlit_multichat:/app --name streamlitmultichat streamlitmultichat:latest /bin/sh -c "cd /app && streamlit run streamlit-multichat.py"
# #podman run -p .....

# #dig multichat.jalcocertech.com

# #docker-compose up -d


# version: '3'
# services:
#   streamlit-multichat:
#     image: ghcr.io/jalcocert/streamlit-multichat
#     container_name: streamlit_multichat
#     volumes:
#       - ai_streamlit_multichat:/app
#     working_dir: /app
#     command: /bin/sh -c "\
#       mkdir -p /app/.streamlit && \
#       echo 'OPENAI_API_KEY = \"sk-proj-openaiAPIhere\"' > /app/.streamlit/secrets.toml && \
#       echo 'GROQ_API_KEY = \"gsk_groqAPIhere\"' >> /app/.streamlit/secrets.toml && \
#       echo 'ANTHROPIC_API_KEY = \"sk-ant-yourANTHROPICapihere\"' >> /app/.streamlit/secrets.toml && \      
#       streamlit run Z_multichat.py"
#     ports:
#       - "8501:8501"
#     restart: always
#     environment:
#       MODEL_API_KEY: sk-proj-openaiAPIhere
#       MODEL: gpt-4o-mini      #gpt-4 
#       TEMPERATURE: 0 #dont be creative :)    
#     networks:
#       - caddy-net
#   caddy:
#     image: caddy:latest
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./Caddyfile:/etc/caddy/Caddyfile
#       - ./caddy_data:/data
#       - ./caddy_config:/config
#     networks:
#       - caddy-net
#     restart: unless-stopped

# networks:
#   caddy-net:
#     driver: bridge

# volumes:
#   ai_streamlit_multichat:

