#https://github.com/getlago/lago

#https://www.youtube.com/watch?v=djoClTbsY7c

# > Open-source metering and usage-based billing



#https://docs.getlago.com/integrations/payments/stripe-integration



#https://docs.getlago.com/integrations/alerting/zapier
#https://docs.getlago.com/integrations/alerting/n8n

#https://docs.getlago.com/api-reference/intro