version: '3'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    restart: always
    hostname: 'gitlab.example.com' # Replace with your domain or IP
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com' # Replace with your domain or IP
        # Add any additional configuration options here
    ports:
      - '89:80'
      - '449:443'
      - '29:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:


#version: "3"

networks:
  gitea:
    external: false
  nginx_nginx_network: #optional
    external: true #optional    

#services:
  server:
    image: gitea/gitea:1.14.2
    container_name: gitea
    environment:
      - USER_UID=998
      - USER_GID=100
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
      #- nginx_nginx_network #optional   
    volumes:
      - /srv/confs/gitea3:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3033:3000"
      - "2234:22"
    depends_on:
      - db
 
  db:
    image: linuxserver/mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /srv/databases/gitea3/mysql:/var/lib/mysql

# version: '3'
# services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins2
    ports:
      - 1080:8080
      - 50000:50000
    volumes:
      - jenkins_home2:/var/jenkins_home
    restart: always

volumes:
  jenkins_home2:

# version: '3'

# services:
#   web:
#     image: 'gitlab/gitlab-ce:latest'
#     container_name: 'gitlab'
#     restart: always
#     ports:
#       - '8028:80'
#       - '4430:443'
#       - '23:22'
#     volumes:
#       - 'gitlab-config:/etc/gitlab'
#       - 'gitlab-logs:/var/log/gitlab'
#       - 'gitlab-data:/var/opt/gitlab'
#     networks: ["nginx_default"]    
# networks:
#     nginx_default:
#         external: true 
# volumes:
#   gitlab-config:
#   gitlab-logs:
#   gitlab-data:  

#then go to port 8028 and ...
#### user root & pass -> docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password  ###
#then just use: root/the_pass_you_got


#https://hub.docker.com/r/gitlab/gitlab-ce