#version: "3.8"

services:
  database:
    image: mariadb:10.6
    volumes:
      - drupal_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_password
    ports:
      - "3006:3306" # Only needed for external access, remove for production
    restart: unless-stopped

  drupal:
    image: drupal:latest
    ports:
      - "8050:80"
    volumes:
      - drupal_site_data:/var/www/html/sites
      - drupal_modules_data:/var/www/html/modules
      - drupal_themes_data:/var/www/html/themes
    environment:
      DRUPAL_DB_HOST: database
      DRUPAL_DB_PORT: 3306
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal_user
      DRUPAL_DB_PASSWORD: drupal_password
    depends_on:
      - database
    restart: unless-stopped

volumes:
  drupal_db_data:
  drupal_site_data:
  drupal_modules_data:
  drupal_themes_data: