version: '2'
services:
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/Docker/Kanboard2/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=UVxY26hNL4qmo
      - MYSQL_DATABASE=kanboard
      - MYSQL_USER=kanboard
      - MYSQL_PASSWORD=kanboard
    restart: always
      
  kanboard:
    image: kanboard/kanboard:latest
    #ports:
    # - 89:80
    expose:
      - 80
    volumes:
      - /home/Docker/Kanboard2/Config/kanboard_data:/var/www/app/data
      - /home/Docker/Kanboard2/Config/kanboard_plugins:/var/www/app/plugins
      - /home/Docker/Kanboard2/Config/kanboard_ssl:/etc/nginx/ssl
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=kanboard
      - DATABASE_PASSWORD=kanboard
      - DATABASE_NAME=kanboard
    depends_on:
      - db
    links:
      - db:db
    restart: always
    networks: ["nginx_default"]    
networks:
    nginx_default:
        external: true    
