version: "3.3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8200:8081"
    volumes:
      - /home/Docker/metube_downloads:/downloads
