#docker run --rm -v /home/ubuntu/docker/hugo/your-website:/src klakegg/hugo:0.101.0 new posts/hello-world.md

version: '3.8'
services:
  server:
    image: klakegg/hugo:0.101.0
    container_name: hugo
    # Key change for network accessibility:
    command: server --bind 0.0.0.0 --port 1313 --baseURL http://192.168.1.11:80/ # Adjust baseURL
    volumes:
      - "/home/ubuntu/docker/hugo/your-website:/src"
    ports:
      - "1313:1313" # Maps host port 80 to container port 1313
                 # Or use "8080:1313" if you prefer a non-privileged port
    # No networks or labels related to Traefik needed for direct local exposure

# ## MAKE SURE YOU RUN THE SITE BUILD COMMAND FIRST, BEFORE DEPLOYING THIS CONTAINER ##
# ## YOU NEED TO MOUNT THE SITE DURING THE HUGO DEPLOYMENT ##

# version: '3.8'
# services:
#   server:
#     image: klakegg/hugo:0.101.0 #https://github.com/klakegg/hugo
#     container_name: hugo
#     command: server --bind 0.0.0.0 --port 1313 # Add --bind 0.0.0.0 to ensure Hugo listens on all interfaces
#     volumes:
#       - "/home/ubuntu/docker/hugo/your-website:/src" #CHANGE THIS!!! mount your site here after you've created a new site!
#     ports:
#       - "1313:1313" # Maps host port 80 to container port 1313
#                  # You can choose any available host port, e.g., "8080:1313"
#     # networks: # Remove this entire section if you're not using any other custom networks
#     #   proxy:
#     # labels: # Remove all Traefik labels
#     #   - "traefik.enable=true"
#     #   - "traefik.http.routers.hugo.entrypoints=http"
#     #   - "traefik.http.routers.hugo.rule=Host(`mywebsite.yourdomain.com`)"
#     #   - "traefik.http.middlewares.hugo-https-redirect.redirectscheme.scheme=https"
#     #   - "traefik.http.routers.hugo.middlewares=hugo-https-redirect"
#     #   - "traefik.http.routers.hugo-secure.entrypoints=https"
#     #   - "traefik.http.routers.hugo-secure.rule=Host(`mywebsite.yourdomain.com`)"
#     #   - "traefik.http.routers.hugo-secure.tls=true"
#     #   - "traefik.http.routers.hugo-secure.service=hugo"
#     #   - "traefik.http.services.hugo.loadbalancer.server.port=1313"
#     #   - "traefik.docker.network=proxy"

# # networks: # Remove this entire section if you're not using any other custom networks
# #   proxy:
# #     external: true