version: '3'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg13 # Adjust the image tag as needed
    container_name: timescaledb_dsb_container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - timescaledb_data_dsb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # networks:
    #   - dsb_network