# version: '3'
# services:
#   esphome:
#     image: esphome/esphome
#     container_name: esphome
#     volumes:
#       - /home/Docker/esphome_config:/config  # Maps the local esphome_config directory to the container's config directory
#       - /etc/localtime:/etc/localtime:ro  # Optional: for time synchronization
#     ports:
#       - "6052:6052"  # ESPHome API
#       - "6123:6123"  # ESPHome Dashboard
#     restart: unless-stopped
#     network_mode: host  # Optional: Use host networking for mDNS discovery



#https://esphome.io/guides/getting_started_command_line.html


version: '3'
services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - /home/Docker/esphome_config:/config  # Maps the local esphome_config directory to the container's config directory
      - /etc/localtime:/etc/localtime:ro  # Optional: for time synchronization
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=test
      - PASSWORD=ChangeMe