#https://docs.directus.io/self-hosted/quickstart.html


# version: "3"
# services:
#   database:
#     image: postgis/postgis:13-master
#     # Required when running on platform other than amd64, like Apple M1/M2:
#     # platform: linux/amd64
#     volumes:
#       - ./data/database:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: "directus"
#       POSTGRES_PASSWORD: "directus"
#       POSTGRES_DB: "directus"

#   cache:
#     image: redis:6

#   directus:
#     image: directus/directus:10.10.5
#     ports:
#       - 8055:8055
#     volumes:
#       - ./uploads:/directus/uploads
#       - ./extensions:/directus/extensions
#     depends_on:
#       - cache
#       - database
#     environment:
#       KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
#       SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

#       DB_CLIENT: "pg"
#       DB_HOST: "database"
#       DB_PORT: "5432"
#       DB_DATABASE: "directus"
#       DB_USER: "directus"
#       DB_PASSWORD: "directus"

#       CACHE_ENABLED: "true"
#       CACHE_STORE: "redis"
#       REDIS: "redis://cache:6379"

#       ADMIN_EMAIL: "admin@example.com"
#       ADMIN_PASSWORD: "d1r3ctu5"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"

    # Environment variables can also be defined in a file (for example `.env`):
    # env_file:
    #- .env

###############################

# version: "3"
# services:
#   directus:
#     image: directus/directus:10.10.5 #https://hub.docker.com/r/directus/directus/
#     ports:
#       - 8055:8055
#     volumes:
#       - ./database:/directus/database
#       - ./uploads:/directus/uploads
#       - ./extensions:/directus/extensions
#     environment:
#       KEY: "replace-with-random-value"
#       SECRET: "replace-with-random-value"
#       ADMIN_EMAIL: "admin@example.com"
#       ADMIN_PASSWORD: "d1r3ctu5"
#       #DB_CLIENT: "sqlite3"
#       #DB_FILENAME: "/directus/database/data.db"
#       WEBSOCKETS_ENABLED: "true"


#docker-compose -f Directus_Docker-compose.yml up


#https://www.youtube.com/watch?v=J7tFWxAGkh4
#https://www.youtube.com/watch?v=RceFoASxO00
services:
    directus:
        image: directus/directus:11.5.1
        ports:
            - 8055:8055
        # volumes:
        #     - ./database:/directus/database
        #     - ./uploads:/directus/uploads
        #     - ./extensions:/directus/extensions
        volumes:
        - database:/directus/database
        - uploads:/directus/uploads
        - extensions:/directus/extensions         
        environment:
            SECRET: "replace-with-random-value"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "d1r3ctu5"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"

volumes:
  database:
  uploads:
  extensions: