---
version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/Docker/freshrss/config:/config
    #ports:
    #  - 8200:80
    expose:
      - "80"
    restart: unless-stopped
    networks: ["nginx_default"]    
networks:
    nginx_default:
        external: true 
