version: "3.3"

services:
    synapse:
        image: "matrixdotorg/synapse:latest"
        container_name: "synapse"
        volumes:
            - "./data:/data"
        environment:
            VIRTUAL_HOST: "mtg.fossengineer.com"
            VIRTUAL_PORT: 8008
            LETSENCRYPT_HOST: "mtg.fossengineer.com"
            SYNAPSE_SERVER_NAME: "mtg.fossengineer.com"
            SYNAPSE_REPORT_STATS: "yes"
        networks: ["server"]


networks:
    server:
        external: true
