version: '3.8'

services:
  db:
    image: mariadb:10.11.5-jammy #latest #https://hub.docker.com/_/mariadb/tags
    container_name: shlink-db
    environment:
      MYSQL_ROOT_PASSWORD: 123abc
      MYSQL_DATABASE: shlink
      MYSQL_USER: root
      MYSQL_PASSWORD: 123abc
    volumes:
      - db-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  shlink:
    image: shlinkio/shlink:stable
    container_name: my_shlink
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DEFAULT_DOMAIN: s.test
      IS_HTTPS_ENABLED: "true"
      #GEOLITE_LICENSE_KEY: kjh23ljkbndskj345 #not mandatory, if not provided, geoloc not working
      DB_DRIVER: mysql  # MariaDB is a drop-in replacement, the driver remains 'mysql'
      DB_USER: root
      DB_PASSWORD: 123abc
      DB_HOST: db  # Use the service name as the hostname for inter-container communication
    restart: unless-stopped

volumes:
  db-data: