version: '3.1'

services:

  ghost:
    image: ghost:4-alpine #https://hub.docker.com/_/ghost/
    container_name: ghost_rpi
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./ghost_data:/var/lib/mysql
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      #url: http://localhost:8080
      url: http://192.168.3.241:2368
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development

  db:
     image: hypriot/rpi-mysql
     container_name: ghost_db
     ports:
      - 3306:3306
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ghost
       MYSQL_DATABASE: ghost
       MYSQL_USER: ghost
       MYSQL_PASSWORD: ghost


#  db:
#    image: mysql:8.0
#    container_name: ghost_db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example

#https://hub.docker.com/_/ghost/
############################

# version: '3.1'

# services:

#   ghost:
#     image: ghost:4-alpine
#     container_name: ghost_rpi
#     restart: always
#     ports:
#       - 2368:2368
#     volumes:
#       - ./ghost_data:/var/lib/mysql
#     environment:
#       # see https://ghost.org/docs/config/#configuration-options
#       database__client: mysql
#       database__connection__host: ghost
#       database__connection__user: ghost
#       database__connection__password: ghost
#       database__connection__database: ghost
#       # this url value is just an example, and is likely wrong for your environment!
#       #url: http://localhost:8080
#       url: http://192.168.3.241:2368
#       # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
#       #NODE_ENV: development

#   db:
#     image: mysql:8.0
#     container_name: ghost_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: example