#!/bin/sh

#wget  -cO - https://raw.githubusercontent.com/reisikei/docker/main/Web/wordpress > wp.sh && chmod 775 wp.sh && sudo ./wp.sh

mkdir Docker
cd Docker
mkdir wordpress
cd wordpress
wget  -cO - https://raw.githubusercontent.com/reisikei/docker/main/Web/Wordpress%20Docker%20Compose.yml > docker-compose.yaml
docker compose up -d
