version: '3.6'

services:
  wordpress:
    image: wordpress:5.7.2
    ports:
      - 87:80 #choose another host port to avoid conflicts
    environment:
      - "WORDPRESS_DB_USER=root"
      - "WORDPRESS_DB_PASSWORD=vFvpKjJ7HUbkD3wyLDp4"
    restart: always
    dns: 8.8.8.8
    volumes: 
      #- /srv/wordpress:/var/www/html
      - ~/Docker/WP/wordpress:/var/www/html

  mysql:
    image: jsurf/rpi-mariadb
    volumes:
    #- /srv/wordpress-mysql:/var/lib/mysql
    - ~/Docker/WP/wordpress-mysql:/var/lib/mysql
    environment:
    - "MYSQL_ROOT_PASSWORD=vFvpKjJ7HUbkD3wyLDp4"
    - "MYSQL_DATABASE=wordpress"
    restart: always

  phpmyadmin:
    image: phpmyadmin:apache
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 9999:80
    volumes:
     #- /sessions
     - ~/Docker/WP/sessions




version: '2.1'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 87:80
    environment:
      PUID: 1000
      PGID: 100
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: changeme
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ~/Docker/WP/wordpress:/var/www/html
    links:
      - db:db
  db:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ=Europe/London
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=changeme #Must match the above password
    volumes:
      - ~/Docker/WP/Wordpressdb:/config
    ports:
      - 3333:3306
    restart: unless-stopped
volumes:
  wordpress:
  db:






version: '3.3'

services:
   db:
     image: hypriot/rpi-mysql
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - wpsite

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - '8088:80'
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: password
     networks:
       - wpsite    


   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - '8008:80'
     restart: always
     volumes: ['./:/var/www/html']
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
       - wpsite
networks:
   wpsite:
volumes:
   db_data:
